// Gerado automaticamente — 196 países (ISO-3166 alpha-2 + DDI)

export const PAISES = [
  { nome: 'Afeganistão', codigo: 'AF', telefone: '93' },
  { nome: 'África do Sul', codigo: 'ZA', telefone: '27' },
  { nome: 'Albânia', codigo: 'AL', telefone: '355' },
  { nome: 'Alemanha', codigo: 'DE', telefone: '49' },
  { nome: 'Andorra', codigo: 'AD', telefone: '376' },
  { nome: 'Angola', codigo: 'AO', telefone: '244' },
  { nome: 'Arábia Saudita', codigo: 'SA', telefone: '966' },
  { nome: 'Argélia', codigo: 'DZ', telefone: '213' },
  { nome: 'Argentina', codigo: 'AR', telefone: '54' },
  { nome: 'Armênia', codigo: 'AM', telefone: '374' },
  { nome: 'Austrália', codigo: 'AU', telefone: '61' },
  { nome: 'Áustria', codigo: 'AT', telefone: '43' },
  { nome: 'Azerbaijão', codigo: 'AZ', telefone: '994' },
  { nome: 'Bahamas', codigo: 'BS', telefone: '1242' },
  { nome: 'Bangladesh', codigo: 'BD', telefone: '880' },
  { nome: 'Barbados', codigo: 'BB', telefone: '1246' },
  { nome: 'Bélgica', codigo: 'BE', telefone: '32' },
  { nome: 'Belize', codigo: 'BZ', telefone: '501' },
  { nome: 'Benin', codigo: 'BJ', telefone: '229' },
  { nome: 'Bielorrússia', codigo: 'BY', telefone: '375' },
  { nome: 'Bolívia', codigo: 'BO', telefone: '591' },
  { nome: 'Bósnia e Herzegovina', codigo: 'BA', telefone: '387' },
  { nome: 'Botsuana', codigo: 'BW', telefone: '267' },
  { nome: 'Brasil', codigo: 'BR', telefone: '55' },
  { nome: 'Brunei', codigo: 'BN', telefone: '673' },
  { nome: 'Bulgária', codigo: 'BG', telefone: '359' },
  { nome: 'Burkina Faso', codigo: 'BF', telefone: '226' },
  { nome: 'Burundi', codigo: 'BI', telefone: '257' },
  { nome: 'Butão', codigo: 'BT', telefone: '975' },
  { nome: 'Cabo Verde', codigo: 'CV', telefone: '238' },
  { nome: 'Camarões', codigo: 'CM', telefone: '237' },
  { nome: 'Camboja', codigo: 'KH', telefone: '855' },
  { nome: 'Canadá', codigo: 'CA', telefone: '1' },
  { nome: 'Catar', codigo: 'QA', telefone: '974' },
  { nome: 'Cazaquistão', codigo: 'KZ', telefone: '7' },
  { nome: 'Chade', codigo: 'TD', telefone: '235' },
  { nome: 'Chile', codigo: 'CL', telefone: '56' },
  { nome: 'China', codigo: 'CN', telefone: '86' },
  { nome: 'Chipre', codigo: 'CY', telefone: '357' },
  { nome: 'Colômbia', codigo: 'CO', telefone: '57' },
  { nome: 'Comores', codigo: 'KM', telefone: '269' },
  { nome: 'Congo', codigo: 'CG', telefone: '242' },
  { nome: 'Coreia do Norte', codigo: 'KP', telefone: '850' },
  { nome: 'Coreia do Sul', codigo: 'KR', telefone: '82' },
  { nome: 'Costa do Marfim', codigo: 'CI', telefone: '225' },
  { nome: 'Costa Rica', codigo: 'CR', telefone: '506' },
  { nome: 'Croácia', codigo: 'HR', telefone: '385' },
  { nome: 'Cuba', codigo: 'CU', telefone: '53' },
  { nome: 'Dinamarca', codigo: 'DK', telefone: '45' },
  { nome: 'Djibuti', codigo: 'DJ', telefone: '253' },
  { nome: 'Dominica', codigo: 'DM', telefone: '1767' },
  { nome: 'Egito', codigo: 'EG', telefone: '20' },
  { nome: 'El Salvador', codigo: 'SV', telefone: '503' },
  { nome: 'Emirados Árabes', codigo: 'AE', telefone: '971' },
  { nome: 'Equador', codigo: 'EC', telefone: '593' },
  { nome: 'Eritreia', codigo: 'ER', telefone: '291' },
  { nome: 'Eslováquia', codigo: 'SK', telefone: '421' },
  { nome: 'Eslovênia', codigo: 'SI', telefone: '386' },
  { nome: 'Espanha', codigo: 'ES', telefone: '34' },
  { nome: 'Estados Unidos', codigo: 'US', telefone: '1' },
  { nome: 'Estônia', codigo: 'EE', telefone: '372' },
  { nome: 'Etiópia', codigo: 'ET', telefone: '251' },
  { nome: 'Fiji', codigo: 'FJ', telefone: '679' },
  { nome: 'Filipinas', codigo: 'PH', telefone: '63' },
  { nome: 'Finlândia', codigo: 'FI', telefone: '358' },
  { nome: 'França', codigo: 'FR', telefone: '33' },
  { nome: 'Gabão', codigo: 'GA', telefone: '241' },
  { nome: 'Gâmbia', codigo: 'GM', telefone: '220' },
  { nome: 'Gana', codigo: 'GH', telefone: '233' },
  { nome: 'Geórgia', codigo: 'GE', telefone: '995' },
  { nome: 'Granada', codigo: 'GD', telefone: '1473' },
  { nome: 'Grécia', codigo: 'GR', telefone: '30' },
  { nome: 'Guatemala', codigo: 'GT', telefone: '502' },
  { nome: 'Guiana', codigo: 'GY', telefone: '592' },
  { nome: 'Guiné', codigo: 'GN', telefone: '224' },
  { nome: 'Guiné Equatorial', codigo: 'GQ', telefone: '240' },
  { nome: 'Guiné-Bissau', codigo: 'GW', telefone: '245' },
  { nome: 'Haiti', codigo: 'HT', telefone: '509' },
  { nome: 'Holanda', codigo: 'NL', telefone: '31' },
  { nome: 'Honduras', codigo: 'HN', telefone: '504' },
  { nome: 'Hong Kong', codigo: 'HK', telefone: '852' },
  { nome: 'Hungria', codigo: 'HU', telefone: '36' },
  { nome: 'Iêmen', codigo: 'YE', telefone: '967' },
  { nome: 'Ilhas Marshall', codigo: 'MH', telefone: '692' },
  { nome: 'Ilhas Maurício', codigo: 'MU', telefone: '230' },
  { nome: 'Ilhas Salomão', codigo: 'SB', telefone: '677' },
  { nome: 'Índia', codigo: 'IN', telefone: '91' },
  { nome: 'Indonésia', codigo: 'ID', telefone: '62' },
  { nome: 'Irã', codigo: 'IR', telefone: '98' },
  { nome: 'Iraque', codigo: 'IQ', telefone: '964' },
  { nome: 'Irlanda', codigo: 'IE', telefone: '353' },
  { nome: 'Islândia', codigo: 'IS', telefone: '354' },
  { nome: 'Israel', codigo: 'IL', telefone: '972' },
  { nome: 'Itália', codigo: 'IT', telefone: '39' },
  { nome: 'Jamaica', codigo: 'JM', telefone: '1876' },
  { nome: 'Japão', codigo: 'JP', telefone: '81' },
  { nome: 'Jordânia', codigo: 'JO', telefone: '962' },
  { nome: 'Kuwait', codigo: 'KW', telefone: '965' },
  { nome: 'Laos', codigo: 'LA', telefone: '856' },
  { nome: 'Lesoto', codigo: 'LS', telefone: '266' },
  { nome: 'Letônia', codigo: 'LV', telefone: '371' },
  { nome: 'Líbano', codigo: 'LB', telefone: '961' },
  { nome: 'Libéria', codigo: 'LR', telefone: '231' },
  { nome: 'Líbia', codigo: 'LY', telefone: '218' },
  { nome: 'Liechtenstein', codigo: 'LI', telefone: '423' },
  { nome: 'Lituânia', codigo: 'LT', telefone: '370' },
  { nome: 'Luxemburgo', codigo: 'LU', telefone: '352' },
  { nome: 'Macau', codigo: 'MO', telefone: '853' },
  { nome: 'Macedônia do Norte', codigo: 'MK', telefone: '389' },
  { nome: 'Madagascar', codigo: 'MG', telefone: '261' },
  { nome: 'Malásia', codigo: 'MY', telefone: '60' },
  { nome: 'Malawi', codigo: 'MW', telefone: '265' },
  { nome: 'Maldivas', codigo: 'MV', telefone: '960' },
  { nome: 'Mali', codigo: 'ML', telefone: '223' },
  { nome: 'Malta', codigo: 'MT', telefone: '356' },
  { nome: 'Marrocos', codigo: 'MA', telefone: '212' },
  { nome: 'Mauritânia', codigo: 'MR', telefone: '222' },
  { nome: 'México', codigo: 'MX', telefone: '52' },
  { nome: 'Mianmar', codigo: 'MM', telefone: '95' },
  { nome: 'Micronésia', codigo: 'FM', telefone: '691' },
  { nome: 'Moçambique', codigo: 'MZ', telefone: '258' },
  { nome: 'Moldávia', codigo: 'MD', telefone: '373' },
  { nome: 'Mônaco', codigo: 'MC', telefone: '377' },
  { nome: 'Mongólia', codigo: 'MN', telefone: '976' },
  { nome: 'Montenegro', codigo: 'ME', telefone: '382' },
  { nome: 'Namíbia', codigo: 'NA', telefone: '264' },
  { nome: 'Nauru', codigo: 'NR', telefone: '674' },
  { nome: 'Nepal', codigo: 'NP', telefone: '977' },
  { nome: 'Nicarágua', codigo: 'NI', telefone: '505' },
  { nome: 'Níger', codigo: 'NE', telefone: '227' },
  { nome: 'Nigéria', codigo: 'NG', telefone: '234' },
  { nome: 'Noruega', codigo: 'NO', telefone: '47' },
  { nome: 'Nova Zelândia', codigo: 'NZ', telefone: '64' },
  { nome: 'Omã', codigo: 'OM', telefone: '968' },
  { nome: 'Palau', codigo: 'PW', telefone: '680' },
  { nome: 'Palestina', codigo: 'PS', telefone: '970' },
  { nome: 'Panamá', codigo: 'PA', telefone: '507' },
  { nome: 'Papua Nova Guiné', codigo: 'PG', telefone: '675' },
  { nome: 'Paquistão', codigo: 'PK', telefone: '92' },
  { nome: 'Paraguai', codigo: 'PY', telefone: '595' },
  { nome: 'Peru', codigo: 'PE', telefone: '51' },
  { nome: 'Polônia', codigo: 'PL', telefone: '48' },
  { nome: 'Porto Rico', codigo: 'PR', telefone: '1' },
  { nome: 'Portugal', codigo: 'PT', telefone: '351' },
  { nome: 'Quênia', codigo: 'KE', telefone: '254' },
  { nome: 'Quirguistão', codigo: 'KG', telefone: '996' },
  { nome: 'Reino Unido', codigo: 'GB', telefone: '44' },
  { nome: 'República Centro-Africana', codigo: 'CF', telefone: '236' },
  { nome: 'República Democrática do Congo', codigo: 'CD', telefone: '243' },
  { nome: 'República Dominicana', codigo: 'DO', telefone: '1' },
  { nome: 'República Tcheca', codigo: 'CZ', telefone: '420' },
  { nome: 'Romênia', codigo: 'RO', telefone: '40' },
  { nome: 'Ruanda', codigo: 'RW', telefone: '250' },
  { nome: 'Rússia', codigo: 'RU', telefone: '7' },
  { nome: 'Samoa', codigo: 'WS', telefone: '685' },
  { nome: 'San Marino', codigo: 'SM', telefone: '378' },
  { nome: 'Santa Lúcia', codigo: 'LC', telefone: '1758' },
  { nome: 'São Cristóvão e Névis', codigo: 'KN', telefone: '1869' },
  { nome: 'São Tomé e Príncipe', codigo: 'ST', telefone: '239' },
  { nome: 'São Vicente e Granadinas', codigo: 'VC', telefone: '1784' },
  { nome: 'Senegal', codigo: 'SN', telefone: '221' },
  { nome: 'Serra Leoa', codigo: 'SL', telefone: '232' },
  { nome: 'Sérvia', codigo: 'RS', telefone: '381' },
  { nome: 'Seychelles', codigo: 'SC', telefone: '248' },
  { nome: 'Singapura', codigo: 'SG', telefone: '65' },
  { nome: 'Síria', codigo: 'SY', telefone: '963' },
  { nome: 'Somália', codigo: 'SO', telefone: '252' },
  { nome: 'Sri Lanka', codigo: 'LK', telefone: '94' },
  { nome: 'Suazilândia', codigo: 'SZ', telefone: '268' },
  { nome: 'Sudão', codigo: 'SD', telefone: '249' },
  { nome: 'Sudão do Sul', codigo: 'SS', telefone: '211' },
  { nome: 'Suécia', codigo: 'SE', telefone: '46' },
  { nome: 'Suíça', codigo: 'CH', telefone: '41' },
  { nome: 'Suriname', codigo: 'SR', telefone: '597' },
  { nome: 'Tailândia', codigo: 'TH', telefone: '66' },
  { nome: 'Taiwan', codigo: 'TW', telefone: '886' },
  { nome: 'Tajiquistão', codigo: 'TJ', telefone: '992' },
  { nome: 'Tanzânia', codigo: 'TZ', telefone: '255' },
  { nome: 'Timor-Leste', codigo: 'TL', telefone: '670' },
  { nome: 'Togo', codigo: 'TG', telefone: '228' },
  { nome: 'Tonga', codigo: 'TO', telefone: '676' },
  { nome: 'Trinidad e Tobago', codigo: 'TT', telefone: '1868' },
  { nome: 'Tunísia', codigo: 'TN', telefone: '216' },
  { nome: 'Turcomenistão', codigo: 'TM', telefone: '993' },
  { nome: 'Turquia', codigo: 'TR', telefone: '90' },
  { nome: 'Tuvalu', codigo: 'TV', telefone: '688' },
  { nome: 'Ucrânia', codigo: 'UA', telefone: '380' },
  { nome: 'Uganda', codigo: 'UG', telefone: '256' },
  { nome: 'Uruguai', codigo: 'UY', telefone: '598' },
  { nome: 'Uzbequistão', codigo: 'UZ', telefone: '998' },
  { nome: 'Vanuatu', codigo: 'VU', telefone: '678' },
  { nome: 'Vaticano', codigo: 'VA', telefone: '379' },
  { nome: 'Venezuela', codigo: 'VE', telefone: '58' },
  { nome: 'Vietnã', codigo: 'VN', telefone: '84' },
  { nome: 'Zâmbia', codigo: 'ZM', telefone: '260' },
  { nome: 'Zimbábue', codigo: 'ZW', telefone: '263' }
]

export default PAISES
